#kind: CheCluster
#apiVersion: org.eclipse.che/v2
#metadata:
#  name: devspaces
#  namespace: openshift-operators
#spec:
#  components:
#    pluginRegistry:
#      externalPluginRegistries:
#        - url: che-plugin-registry
#  containerRegistry: {}
#  devEnvironments: {}
#  gitServices: {}
#  networking: {}
apiVersion: org.eclipse.che/v2
kind: CheCluster
metadata:
  name: devspaces
  namespace: openshift-operators
spec:
  components:
    pluginRegistry:
      deployment:
        containers:
          - name: plugin-registry
            image: quay.io/danclark/che-plugin-registry:continue
            imagePullPolicy: Always
    cheServer:
      debug: false
      logLevel: INFO
    dashboard:
      logLevel: ERROR
    metrics:
      enable: true
  containerRegistry: {}
  devEnvironments:
    startTimeoutSeconds: 300
    secondsOfRunBeforeIdling: -1
    maxNumberOfWorkspacesPerUser: -1
    containerBuildConfiguration:
      openShiftSecurityContextConstraint: container-build
    ignoredUnrecoverableEvents:
      - FailedScheduling
    defaultNamespace:
      autoProvision: true
      template: <username>-devspaces
    secondsOfInactivityBeforeIdling: 1800
    storage:
      pvcStrategy: per-user
  gitServices: {}
  networking:
    auth:
      gateway:
        kubeRbacProxy:
          logLevel: 0
        oAuthProxy:
          cookieExpireSeconds: 86400
        traefik:
          logLevel: INFO

